name: Echo Secret

on:
  pull_request:
    types: [ opened,synchronize ]
jobs:
  echo-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo Secret
      run: |
        # Access and echo the value of the secret
        echo "The value of the secret MY_SECRET is: ${{ secrets.MY_JSON_SECRET}}"