name: Echo Secret
on: [pull_request, push]
jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    env:
      ACTIONS_REF: ${{ github.base_ref }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Checkout workflows repo # required so we can reference the actions locally
      uses: actions/checkout@v3
      with:
        ref: ${{ env.ACTIONS_REF }}
        path: sharedactions
        repository: dheerajmogaveera/GithubActionsPractice
        token: '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'
        sparse-checkout: |
          .github/actions/test/
    
    - name: Install Node Dependencies
      run: |
        echo "::group::Install Node Dependencies"
        if [ "${{ env.PACKAGE_MANAGER }}" == "pnpm" ]; then
          pnpm install --frozen-lockfile
        else
          npm ci
        fi
        echo "::endgroup::"
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    - name: Echo Secret
      run: |
        # Access and echo the value of the secret
        echo "The value of the secret MY_JSON_SECRET is: ${{ secrets.MY_JSON_SECRET }}"
    - name: Run Action
      id: run-action
      uses:  ./sharedactions/.github/actions/test/
    - name: Echo outputs
      run: |
        echo "The value of the secret MY_JSON_SECRET is: ${{ steps.run-action.outputs.secret}}"
      